// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cixyffxeygmwqelcwuly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpeHlmZnhleWdtd3FlbGN3dWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTc1NTUsImV4cCI6MjA3MTk3MzU1NX0.-5tSV0aW4Lzc1oZQcSoJjikkl2L_RdOcP9rX90BGe8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});